services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./AI-VocabGen-main/Back-End/.env
    volumes:
      - ./AI-VocabGen-main/Back-End/:/app
